### ISSUE TITLE
custom single player mission crashing

### ISSUE THREAD

**Issue by danielkorg** [Nyerguds/MobiusMapEditor#8]
[TestMission01.zip](https://github.com/user-attachments/files/16830285/TestMission01.zip)

I attached my custom mission. It's actually the very first time I am using Mobius editor to make a mission, so
it is very possible I did something wrong. The mission only has one GDI apc, and 5 nod minigunners.

I put the lose and win triggers. Lose trigger works, but when I want to try and crush the minigunners with my apc,
the game crashes, I don't know why. Can you check my mission and figure out why that would happen?

I am using the latest Mobius version 1.5.0.3.

Thank you!

**Comment by Nyerguds** [comment]
This is a bug tracker for the map editor, not a mission scripting support board. You can ask about such issues on the Discord, but I won't accept them here in the bug tracker.
